version: '3.9'

services:
  backend:
    image: riunguflo/yolo-backend:v1.0.0
    container_name: yolo-backend
    ports:
      - "5000:5000"
    restart: always

  client:
    image: riunguflo/yolo-client:v1.0.0
    container_name: yolo-client
    ports:
      - "80:3000"  # nginx on port 80 serving React on internal port 3000
    restart: always