- name: Deploy E-commerce App with Docker
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  roles:

    - ecommerce
    - database
    - common
    - backend
    - client
    - compose_up